Assignment Name : Data Doctor
Description : Clean a dataset by handling missing values, removing duplicates, standardizing text, and explain why cleaning matters.

In [1]:
import pandas as pd
data = pd.read_csv("messy_data.csv")
df = pd.DataFrame(data)

In [2]:
df.sample(5)

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
4,105,John Doe,john@gmail.com,Bangalore,2500,2024-01-05
3,104,Anita Sharma,anita@gmail.com,Chennai,2200,NaN
8,109,NaN,noemail@,Kolkata,1600,2024-01-11
5,106,Ali Khan,NaN,Hyderabad,1500,2024-01-08
7,108,Sunil Gupta,sunil@gmail.com,Delhi,1700,2024-01-10

In [3]:
# Step 1 : Understand the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   10 non-null     int64
 1   Name          9 non-null      object
 2   Email         9 non-null      object
 3   City          10 non-null     object
 4   Order_Amount  9 non-null      object
 5   Order_Date    9 non-null      object
dtypes: int64(1), object(5)
memory usage: 608.0+ bytes

In [4]:
df.shape

(10, 6)

In [5]:
df.columns

Index(['Customer_ID', 'Name', 'Email', 'City', 'Order_Amount', 'Order_Date'], dtype='object')

In [6]:
# Step 2: Handle duplicates
df.duplicated(subset=["Name","Email","City","Order_Amount","Order_Date"])

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [7]:
df.drop_duplicates(subset=["Name","Email","City","Order_Amount","Order_Date"])

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,Bangalore,2500,2024-01-05
1,102,Jane Smith,jane@gmail.com,Mumbai,1800,2024-01-06
2,103,Ravi Kumar,ravi@gmail.com,delhi,NaN,2024-01-07
3,104,Anita Sharma,anita@gmail.com,Chennai,2200,NaN
5,106,Ali Khan,NaN,Hyderabad,1500,2024-01-08
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,Delhi,1700,2024-01-10
8,109,NaN,noemail@,Kolkata,1600,2024-01-11
9,110,Neha Verma,neha@gmail.com,Bangalore,abc,2024-01-12

In [8]:
# Step 3: Standardizing text data

df['City']=df['City'].str.upper()

In [9]:
df

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
1,102,Jane Smith,jane@gmail.com,MUMBAI,1800,2024-01-06
2,103,Ravi Kumar,ravi@gmail.com,DELHI,NaN,2024-01-07
3,104,Anita Sharma,anita@gmail.com,CHENNAI,2200,NaN
4,105,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
5,106,Ali Khan,NaN,HYDERABAD,1500,2024-01-08
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,DELHI,1700,2024-01-10
8,109,NaN,noemail@,KOLKATA,1600,2024-01-11
9,110,Neha Verma,neha@gmail.com,BANGALORE,abc,2024-01-12

In [10]:
# Step 4: Handle Missing Values
''' NaN - Not a number
None
empty cells'''
df.isnull()

   Customer_ID   Name  Email   City  Order_Amount  Order_Date
0        False  False  False  False         False       False
1        False  False  False  False         False       False
2        False  False  False  False          True       False
3        False  False  False  False         False        True
4        False  False  False  False         False       False
5        False  False   True  False         False       False
6        False  False  False  False         False       False
7        False  False  False  False         False       False
8        False   True  False  False         False       False
9        False  False  False  False         False       False

In [11]:
df.isnull().sum()

Customer_ID     0
Name            1
Email           1
City            0
Order_Amount    1
Order_Date      1
dtype: int64

In [12]:
# remove missing values
df.dropna()

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
1,102,Jane Smith,jane@gmail.com,MUMBAI,1800,2024-01-06
4,105,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,DELHI,1700,2024-01-10
9,110,Neha Verma,neha@gmail.com,BANGALORE,abc,2024-01-12

In [13]:
df.dropna(axis=0)
# axis = 0 -> rows
# axis = 1 -> columns

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
1,102,Jane Smith,jane@gmail.com,MUMBAI,1800,2024-01-06
4,105,John Doe,john@gmail.com,BANGALORE,2500,2024-01-05
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,DELHI,1700,2024-01-10
9,110,Neha Verma,neha@gmail.com,BANGALORE,abc,2024-01-12

In [16]:
df['Order_Amount'] = pd.to_numeric(df['Order_Amount'],errors='coerce')
df['Order_Date'] = pd.to_datetime(df['Order_Date'],errors='coerce')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   10 non-null     int64
 1   Name          9 non-null      object
 2   Email         9 non-null      object
 3   City          10 non-null     object
 4   Order_Amount  8 non-null      float64
 5   Order_Date    9 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(3)
memory usage: 608.0+ bytes

In [18]:
df

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,BANGALORE,2500.0,2024-01-05
1,102,Jane Smith,jane@gmail.com,MUMBAI,1800.0,2024-01-06
2,103,Ravi Kumar,ravi@gmail.com,DELHI,NaN,2024-01-07
3,104,Anita Sharma,anita@gmail.com,CHENNAI,2200.0,NaT
4,105,John Doe,john@gmail.com,BANGALORE,2500.0,2024-01-05
5,106,Ali Khan,NaN,HYDERABAD,1500.0,2024-01-08
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000.0,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,DELHI,1700.0,2024-01-10
8,109,NaN,noemail@,KOLKATA,1600.0,2024-01-11
9,110,Neha Verma,neha@gmail.com,BANGALORE,NaN,2024-01-12

In [27]:
# fill missing values
# for numerical columns ->mean/median
df['Order_Amount'].fillna(df['Order_Amount'].mean(),inplace=True)

C:\Users\Manish Chaudhary\AppData\Local\Temp\ipykernel_15380\563355325.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Amount'].fillna(df['Order_Amount'].mean(),inplace=True)

In [29]:
# filling missing values in categorical columns

df['Email'].fillna(df['Name'].str.split().str[0].str.lower() + '@gmail.com',inplace = True)

C:\Users\Manish Chaudhary\AppData\Local\Temp\ipykernel_15380\1476162158.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Email'].fillna(df['Name'].str.split().str[0].str.lower() + '@gmail.com',inplace = True)

In [31]:
df.dropna(inplace = True)

In [32]:
df

,Customer_ID,Name,Email,City,Order_Amount,Order_Date
0,101,John Doe,john@gmail.com,BANGALORE,2500.0,2024-01-05
1,102,Jane Smith,jane@gmail.com,MUMBAI,1800.0,2024-01-06
2,103,Ravi Kumar,ravi@gmail.com,DELHI,1975.0,2024-01-07
4,105,John Doe,john@gmail.com,BANGALORE,2500.0,2024-01-05
5,106,Ali Khan,ali@gmail.com,HYDERABAD,1500.0,2024-01-08
6,107,Priya Singh,priya@gmail.com,MUMBAI,2000.0,2024-01-09
7,108,Sunil Gupta,sunil@gmail.com,DELHI,1700.0,2024-01-10
9,110,Neha Verma,neha@gmail.com,BANGALORE,1975.0,2024-01-12

Why does cleaning matter?
Data cleaning is important because it removes errors, handles missing values, and ensures accurate, reliable analysis and decision-making.